spring:
  kafka:
    bootstrap-servers:
    - 192.168.3.2:32774
    
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true