spring:
  kafka:
    bootstrap-servers:
    - kafka:9092
    
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true